@RepositoryPatternWebApi_HostAddress = https://localhost:7258

GET {{RepositoryPatternWebApi_HostAddress}}/

###

GET {{RepositoryPatternWebApi_HostAddress}}/api/products
Accept: application/json

###


GET {{RepositoryPatternWebApi_HostAddress}}/api/products/3
Accept: application/json

###