@https = https://localhost:7258
@http = http://localhost:5141

# Choose the base URL that matches the running profile (change to {{http}}, {{iisExpressHttps}}, or {{iisExpressHttp}} as needed)
@base = {{https}}

###
GET {{base}}/

###
GET {{base}}/api/products
Accept: application/json

###
POST {{base}}/api/products
Accept: application/json
Content-Type: application/json

{
  "Name": "Sample productm 9",
  "Description": "Sample description",
  "Price": 9999.99,
  "CategoryId": 3,
  "CategoryName": "BLL"
}

###
GET {{base}}/api/products/3
Accept: application/json



