@RepositoryPatternWebApi_HostAddress = https://localhost:7258
@https = https://localhost:7258
@http = http://localhost:5141

# Choose the base URL that matches the running profile (change to {{http}}, {{iisExpressHttps}}, or {{iisExpressHttp}} as needed)
@base = {{https}}

###
GET {{base}}/

###
GET {{base}}/api/products
Accept: application/json

###
POST {{base}}/api/products
Accept: application/json
Content-Type: application/json

{
  "Name": "Sample productm 9",
  "Description": "Sample description",
  "Price": 9999.99,
  "CategoryId": 3,
  "CategoryName": "BLL"
}

###
GET {{base}}/api/products/3
Accept: application/json

###

@id=12
DELETE {{RepositoryPatternWebApi_HostAddress}}/api/products/{{id}}

###

PUT {{RepositoryPatternWebApi_HostAddress}}/api/products/{{id}}
Content-Type: application/json

{
  //ProductDTO
}

###
# Dependency Injection types example

GET {{base}}/api/randomService


###
# Location Controller

{{base}}/api/location/countries


###
@id = 2
{{base}}/api/location/states/{{id}}


###

{{base}}/api/location/cities/{{id}}


###